//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package si.fb.posiljanjeobvestilstoritev;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import si.fb.posiljanjeobvestilstoritevsporocila.ObjectFactory;
import si.fb.posiljanjeobvestilstoritevsporocila.SporociloTip;
import si.fb.posiljanjeobvestilstoritevsporocila.TipSporocilaResponseEnum;

@WebService(name = "PosiljanjeObvestilStoritev", targetNamespace = "http://www.fb.si/PosiljanjeObvestilStoritev")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PosiljanjeObvestilStoritev {


    /**
     * 
     * @param posljiSporociloRequest
     * @return
     *     returns si.fb.posiljanjeobvestilstoritevsporocila.TipSporocilaResponseEnum
     */
    @WebMethod(action = "http://www.fb.si/PosiljanjeObvestilStoritev/posljiSporocilo")
    @WebResult(name = "TipSporocilaResponse", targetNamespace = "http://www.fb.si/PosiljanjeObvestilStoritevSporocila", partName = "posljiSporociloResponse")
    public TipSporocilaResponseEnum posljiSporocilo(
        @WebParam(name = "TipSporosilaRequest", targetNamespace = "http://www.fb.si/PosiljanjeObvestilStoritevSporocila", partName = "posljiSporociloRequest")
        SporociloTip posljiSporociloRequest);

}
