//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package si.fb.posiljanjeobvestilstoritevsporocila;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipSporocilaResponseEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipSporocilaResponseEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="OK"/>
 *     &lt;enumeration value="Error"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TipSporocilaResponseEnum")
@XmlEnum
public enum TipSporocilaResponseEnum {

    OK("OK"),
    @XmlEnumValue("Error")
    ERROR("Error");
    private final String value;

    TipSporocilaResponseEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipSporocilaResponseEnum fromValue(String v) {
        for (TipSporocilaResponseEnum c: TipSporocilaResponseEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
